# =====================================================
#        TAGTHEMALL WORKER DOCKERFILE
# =====================================================

FROM node:22-alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

RUN apk add --no-cache dumb-init tzdata ca-certificates

COPY . .

RUN npm install --omit=dev

RUN chown -R appuser:appgroup /app

ENV NODE_ENV=production

USER appuser

EXPOSE 3000

ENTRYPOINT ["dumb-init", "--"]

CMD ["node", "worker/worker.js"]