apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagthemall-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tagthemall-worker
  template:
    metadata:
      labels:
        app: tagthemall-worker
    spec:
      containers:
        - name: worker
          image: simple431/tagthemall-worker:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tagthemall-secrets
                  key: mongodb_uri
            - name: REDIS_ENABLED
              value: "false"
