app = "worker-template"

kill_signal = "SIGINT"
kill_timeout = 30

[build]
  dockerfile = "worker/Dockerfile"

[[mounts]]
  source = "whatsapp_data"
  destination = "/app/.wwebjs_auth"

[[services]]
  internal_port = 5001
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
